keycloak-base-url: http://keycloak:8080

server:
  servlet:
    context-path: /phaedra/pipeline-service

spring:
  application:
    name: phaedra-pipeline-service
  jackson:
    serialization:
      indent_output: true
  liquibase:
    enabled: false
  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
      group-id: phaedra2

logging:
  level:
    root: INFO
    eu.openanalytics.phaedra: DEBUG